# Generated by Django 2.0.8 on 2018-09-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180928_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=str, max_length=32),
            preserve_default=False,
        ),
    ]
