# Generated by Django 2.0.8 on 2018-12-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181125_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='ru', max_length=2),
        ),
    ]
