# Generated by Django 2.0.8 on 2018-10-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181005_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.Balance'),
        ),
    ]
