# Generated by Django 2.0.8 on 2018-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181005_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(default='AAAAAAAAA-AAAAAAAAA', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
