# Generated by Django 2.0.8 on 2018-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_with_capitalization', models.BooleanField(default=False)),
                ('grace_period', models.IntegerField(default=0)),
                ('return_period', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_frozen', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_overpay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_credit_period', models.IntegerField()),
                ('fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=3)),
                ('from_id', models.BigIntegerField()),
                ('to_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_with_capitalization', models.BooleanField(default=False)),
                ('grace_period', models.IntegerField(default=0)),
                ('return_period', models.IntegerField()),
                ('credit_fund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_loan_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_loan_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dried', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
