# Generated by Django 2.0.8 on 2018-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20181123_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='used_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
