# Generated by Django 2.0.8 on 2018-11-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20181123_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='dried',
        ),
    ]
