# Generated by Django 2.0.8 on 2018-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20181206_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
