# Generated by Django 2.0.8 on 2018-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20181206_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='total_pay_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
