# Generated by Django 2.0.8 on 2018-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratingsummary',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='userratingsummary',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
