# Generated by Django 2.0.8 on 2018-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20181209_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('base', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('base_rate', models.DecimalField(decimal_places=10, max_digits=50)),
                ('currency_rate', models.DecimalField(decimal_places=10, max_digits=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
